// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=gorilla_fan/design
// --out=$(GOPATH)/src/gorilla_fan
// --version=v1.0.0
//
// API "gorilla_fan": Application Resource Href Factories
//
// The content of this file is auto-generated, DO NOT MODIFY

package app

import (
	"fmt"
	"strings"
)

// FanHref returns the resource href.
func FanHref(fanID interface{}) string {
	paramfanID := strings.TrimLeftFunc(fmt.Sprintf("%v", fanID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/fans/%v", paramfanID)
}

// ThermoHref returns the resource href.
func ThermoHref(thermoID interface{}) string {
	paramthermoID := strings.TrimLeftFunc(fmt.Sprintf("%v", thermoID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/thermo/%v", paramthermoID)
}
