---
- hosts: tag_Name_gorilla_iot
  become: true
  tasks:
  - name: "Install nginx and docker"
    action: >
      {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
    with_items:
      - vim
      - nginx
      - docker
  - name: "Start docker"
    service: name=docker state=started

  - name: "Enable docker"
    service: name=docker state=enabled
